### ISSUE TITLE
the events are not showing

### ISSUE THREAD

**Issue by YuriFontella** [nibdo/kalend#84]
Hi,

I'm using kalend with next.js and for that I had to use the dynamic function to not render server-side.

I'm trying to display events from a fixed state and yet I don't know what I might be doing wrong as they aren't being displayed.

Any suggestions?

```bash
const KalendWithNoSSR = dynamic(
  () => import('@/src/components/pages/kalend'),
  { ssr: false }
)
```

![image](https://user-images.githubusercontent.com/4920619/147790757-37bf0447-a103-4d8e-89f2-e26d0f8a236e.png)

![image](https://user-images.githubusercontent.com/4920619/147790781-da025406-d1d3-457e-935f-6b3ef3f03649.png)

No error is shown.
Thank you.

**Comment by nibdo** [comment]
Hello, this might by issue with way how table with events is rendered.

Flow looks like this:
1. Root element is rendered - this is used as reference to calculate height and width of timetable with events
2. When elements are rendered, then table will start calculations of event layouts.

Step 1 is problem, as it seems dimensions were not set so table with events is still hidden.

I will try to find, how is this happening. What could help might be some more details, how component KalendWithNoSSR is rendered - how does your parent element (where KalendWithNoSSR is placed) looked like (styling mostly) and how is it rendered. Thank you

**Comment by YuriFontella** [comment]
Thanks a lot for the help,

I'm using this dynamic function from next because without it an error like "document is not defined" is generated.

I do it exactly as in the basic form of use, kalend is a component, and I import it into the parent component using this dynamic function with ssr turned off.

[https://nextjs.org/docs/advanced-features/dynamic-import](https://nextjs.org/docs/advanced-features/dynamic-import)

**Comment by nibdo** [comment]
Thanks, I checked it. I could make it work, you just have to be sure that parent elements have some height.

For start, try to set body and all parent elements to width, height 100% and then you can adjust it to your needs. 
Basically Kalend has default height and width to 100% and it is inheriting it from your parent element/s. Or you can also set hard values like height: 500px for "\<main\>" but I think most people need something more dynamic. 

Didn't look at how is this element with id "#__next" used, but you might set it to some height and width too, because by default it doesn't have width, height.
![next](https://user-images.githubusercontent.com/57879411/147796988-7bfe9e44-c890-469d-941a-e0ef8bcf8652.png)

**Comment by YuriFontella** [comment]
That's exactly what it was, setting a height on the parent element of the kalend.
Thanks @nibdo

**Comment by nibdo** [comment]
No problem :)

**Comment by Marteyo** [comment]
Hi, I have the same problem; I am trying to solve it with your suggestions, but it is not working.

Thank you!

![imagen](https://user-images.githubusercontent.com/23101901/175251913-a3167c97-2fbf-4e2c-bac3-de85f60f3238.png)

**Comment by Marteyo** [comment]
> Hi, I have the same problem; I am trying to solve it with your suggestions, but it is not working. I am using "kalend": "^0.14.13".
> 
> Thank you!
> 
> ![imagen](https://user-images.githubusercontent.com/23101901/175251913-a3167c97-2fbf-4e2c-bac3-de85f60f3238.png)

I change the page with the same parameters as the example, and it now works. The problem is that I want to put the calendar inside a [Card ](https://www.primefaces.org/primereact/card/) component, but I can't.

![imagen](https://user-images.githubusercontent.com/23101901/175289205-a4bf0d70-c7b4-4c8d-96e8-97e373c1edc2.png)

**Comment by SengTime** [comment]
> > Hi, I have the same problem; I am trying to solve it with your suggestions, but it is not working. I am using "kalend": "^0.14.13".
> > Thank you!
> > ![imagen](https://user-images.githubusercontent.com/23101901/175251913-a3167c97-2fbf-4e2c-bac3-de85f60f3238.png)
> 
> I change the page with the same parameters as the example, and it now works. The problem is that I want to put the calendar inside a [Card ](https://www.primefaces.org/primereact/card/) component, but I can't.
> 
> ![imagen](https://user-images.githubusercontent.com/23101901/175289205-a4bf0d70-c7b4-4c8d-96e8-97e373c1edc2.png)

Hi,
Try setting the width in the parent control of Card and setting the height in the Card control

<img width="469" alt="image" src="https://user-images.githubusercontent.com/52897984/180593236-089767c4-e96a-4b70-924b-cdc311ef4fa4.png">
<img width="2488" alt="image" src="https://user-images.githubusercontent.com/52897984/180593249-5990d03c-1de2-4473-95c6-96a6d8b0ac95.png">

**Comment by kengkreingkrai** [comment]
In my case, I need to calculate the parent's height for the Kalend
But for the first time, Kalend has rendered there are no events displayed, I have to do something that will refresh the Kalend size to get it work

Anyway, I saw the height of Kelend always equals zero for the first time. (the onStateChange props)

So, I do something for workaround
![image](https://user-images.githubusercontent.com/20807973/205019119-1b4397f7-7daa-418e-a944-027bcb8eb2e5.png)
